name: Build and Push Docker Image
description: Builds docker image, logs in to ECR and pushes the new image to ECR
inputs:
  aws_ecr:
    description: "The ECR base url to push the image into (omit the redis-roaring image name)"
    required: true
  aws_region:
    description: "AWS region"
    default: "us-west-2"
  oidc_role:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.oidc_role }}
        role-session-name: GithubActions
        aws-region: ${{ inputs.aws_region }}
    - name: Login to Amazon ECR
      id: login_ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        AWS_ECR: ${{ inputs.aws_ecr }}
      run: |
        docker buildx build -t $AWS_ECR/redis-roaring:sha_$GITHUB_SHA --output type=docker .
        docker push $AWS_ECR/redis-roaring --all-tags
      shell: bash