#ifndef FUZZ_COMMAND_MANIFEST_H
#define FUZZ_COMMAND_MANIFEST_H

#include <stddef.h>

#include "../../src/redismodule.h"

typedef enum {
  FUZZ_COMMAND_FIXED = 0,
  FUZZ_COMMAND_BITOP,
} FuzzCommandShape;

typedef struct {
  int begin_pos;
  int lastkey;
  int keystep;
  int limit;
  int flags;
} FuzzKeySpecExpectation;

typedef struct {
  int pos;
  int flags;
} FuzzKeyExpectation;

typedef struct {
  const char* name;
  const char* counterpart;
  int redis_arity;
  int min_argc;
  int max_argc;
  FuzzCommandShape shape;
  size_t key_spec_count;
  FuzzKeySpecExpectation key_specs[2];
  size_t expanded_key_count;
  FuzzKeyExpectation expanded_keys[3];
} FuzzCommandDescriptor;

#define FUZZ_KEYSPEC(key_begin_pos, key_lastkey, key_step, key_limit, key_flags) \
  { .begin_pos = (key_begin_pos), .lastkey = (key_lastkey), .keystep = (key_step), .limit = (key_limit), .flags = (key_flags) }

#define FUZZ_PAIR_SINGLE_KEY(suffix, arity, min_argc, max_argc, key_flags) \
  { "R." suffix, "R64." suffix, arity, min_argc, max_argc, FUZZ_COMMAND_FIXED, 1, { FUZZ_KEYSPEC(1, 0, 1, 0, key_flags), {0} }, 1, { {1, key_flags}, {0}, {0} } }, \
  { "R64." suffix, "R." suffix, arity, min_argc, max_argc, FUZZ_COMMAND_FIXED, 1, { FUZZ_KEYSPEC(1, 0, 1, 0, key_flags), {0} }, 1, { {1, key_flags}, {0}, {0} } }

#define FUZZ_PAIR_TWO_KEY_RANGE(suffix, arity, min_argc, max_argc, key_flags) \
  { "R." suffix, "R64." suffix, arity, min_argc, max_argc, FUZZ_COMMAND_FIXED, 1, { FUZZ_KEYSPEC(1, 1, 1, 0, key_flags), {0} }, 2, { {1, key_flags}, {2, key_flags}, {0} } }, \
  { "R64." suffix, "R." suffix, arity, min_argc, max_argc, FUZZ_COMMAND_FIXED, 1, { FUZZ_KEYSPEC(1, 1, 1, 0, key_flags), {0} }, 2, { {1, key_flags}, {2, key_flags}, {0} } }

#define FUZZ_PAIR_DIFF() \
  { "R.DIFF", "R64.DIFF", 4, 4, 4, FUZZ_COMMAND_FIXED, 2, { FUZZ_KEYSPEC(1, 0, 1, 0, REDISMODULE_CMD_KEY_OW | REDISMODULE_CMD_KEY_INSERT), FUZZ_KEYSPEC(2, 2, 1, 0, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS) }, 3, { {1, REDISMODULE_CMD_KEY_OW | REDISMODULE_CMD_KEY_INSERT}, {2, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS}, {3, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS} } }, \
  { "R64.DIFF", "R.DIFF", 4, 4, 4, FUZZ_COMMAND_FIXED, 2, { FUZZ_KEYSPEC(1, 0, 1, 0, REDISMODULE_CMD_KEY_OW | REDISMODULE_CMD_KEY_INSERT), FUZZ_KEYSPEC(2, 2, 1, 0, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS) }, 3, { {1, REDISMODULE_CMD_KEY_OW | REDISMODULE_CMD_KEY_INSERT}, {2, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS}, {3, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS} } }

#define FUZZ_PAIR_BITOP() \
  { "R.BITOP", "R64.BITOP", -4, 4, -1, FUZZ_COMMAND_BITOP, 2, { FUZZ_KEYSPEC(2, 0, 1, 0, REDISMODULE_CMD_KEY_RW | REDISMODULE_CMD_KEY_INSERT), FUZZ_KEYSPEC(3, -1, 1, 0, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS) }, 0, {{0}, {0}, {0}} }, \
  { "R64.BITOP", "R.BITOP", -4, 4, -1, FUZZ_COMMAND_BITOP, 2, { FUZZ_KEYSPEC(2, 0, 1, 0, REDISMODULE_CMD_KEY_RW | REDISMODULE_CMD_KEY_INSERT), FUZZ_KEYSPEC(3, -1, 1, 0, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS) }, 0, {{0}, {0}, {0}} }

static const FuzzCommandDescriptor FUZZ_COMMAND_DESCRIPTORS[] = {
  FUZZ_PAIR_SINGLE_KEY("SETBIT", 4, 4, 4, REDISMODULE_CMD_KEY_RW | REDISMODULE_CMD_KEY_UPDATE),
  FUZZ_PAIR_SINGLE_KEY("GETBIT", 3, 3, 3, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_SINGLE_KEY("GETBITS", -3, 3, -1, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_SINGLE_KEY("CLEARBITS", -3, 3, -1, REDISMODULE_CMD_KEY_RW | REDISMODULE_CMD_KEY_UPDATE),
  FUZZ_PAIR_SINGLE_KEY("SETINTARRAY", -3, 3, -1, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_INSERT),
  FUZZ_PAIR_SINGLE_KEY("GETINTARRAY", 2, 2, 2, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_SINGLE_KEY("RANGEINTARRAY", 4, 4, 4, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_SINGLE_KEY("APPENDINTARRAY", -3, 3, -1, REDISMODULE_CMD_KEY_RW | REDISMODULE_CMD_KEY_INSERT),
  FUZZ_PAIR_SINGLE_KEY("DELETEINTARRAY", -3, 3, -1, REDISMODULE_CMD_KEY_RW | REDISMODULE_CMD_KEY_DELETE),
  FUZZ_PAIR_DIFF(),
  FUZZ_PAIR_SINGLE_KEY("SETFULL", 2, 2, 2, REDISMODULE_CMD_KEY_OW | REDISMODULE_CMD_KEY_INSERT),
  FUZZ_PAIR_SINGLE_KEY("SETRANGE", 4, 4, 4, REDISMODULE_CMD_KEY_RW | REDISMODULE_CMD_KEY_UPDATE),
  FUZZ_PAIR_SINGLE_KEY("OPTIMIZE", -2, 2, 3, REDISMODULE_CMD_KEY_RW | REDISMODULE_CMD_KEY_UPDATE),
  FUZZ_PAIR_SINGLE_KEY("SETBITARRAY", 3, 3, 3, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_INSERT),
  FUZZ_PAIR_SINGLE_KEY("GETBITARRAY", 2, 2, 2, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_BITOP(),
  FUZZ_PAIR_SINGLE_KEY("BITCOUNT", 2, 2, 2, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_SINGLE_KEY("BITPOS", 3, 3, 3, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_SINGLE_KEY("MIN", 2, 2, 2, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_SINGLE_KEY("MAX", 2, 2, 2, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_SINGLE_KEY("CLEAR", 2, 2, 2, REDISMODULE_CMD_KEY_OW | REDISMODULE_CMD_KEY_DELETE),
  FUZZ_PAIR_TWO_KEY_RANGE("CONTAINS", -3, 3, 4, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  FUZZ_PAIR_TWO_KEY_RANGE("JACCARD", 3, 3, 3, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS),
  { "R.STAT", NULL, -2, 2, 3, FUZZ_COMMAND_FIXED, 1, { FUZZ_KEYSPEC(1, 0, 1, 0, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS), {0} }, 1, { {1, REDISMODULE_CMD_KEY_RO | REDISMODULE_CMD_KEY_ACCESS}, {0}, {0} } },
};

static inline size_t fuzz_command_descriptor_count(void) {
  return sizeof(FUZZ_COMMAND_DESCRIPTORS) / sizeof(FUZZ_COMMAND_DESCRIPTORS[0]);
}

#endif
