/* Do not edit: file generated by auxprogs/make_or_upd_vgversion_h.
   This file defines VGSVN and VEXSVN, used to report SVN revision
   when using command line options:  -v --version 
*/
#define VGSVN "16445:16446"
#define VEXSVN "3396"
