#pragma once

#define REDISROARING_VERSION_MAJOR 1
#define REDISROARING_VERSION_MINOR 6
#define REDISROARING_VERSION_PATCH 0

#ifndef REDISROARING_MODULE_NAME
#define REDISROARING_MODULE_NAME "REDIS-ROARING"
#endif

#define REDISROARING_MODULE_VERSION \
  (REDISROARING_VERSION_MAJOR * 10000 + REDISROARING_VERSION_MINOR * 100 + REDISROARING_VERSION_PATCH)
